volumes:
  traefik-certs:
    driver: local

services:
  telegrambotlaurenttransport:
    container_name: telegrambotlaurenttransport
    restart: on-failure
    build:
      context: ./
      dockerfile: ./telegrambotlaurenttransport/Dockerfile
    environment:
      TBLT_PORT: ${SERVER_PORT}
      TG_BOT_NAME: ${TG_BOT_NAME}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_BOT_URI: ${TG_BOT_URI}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.telegrambotlaurenttransport.loadbalancer.server.port=${SERVER_PORT}"
      - "traefik.http.routers.telegrambotlaurenttransport.rule=Host(`${HOST_URL}`) && PathPrefix(`/callback`)"
      - "traefik.http.routers.telegrambotlaurenttransport.entrypoints=websecure8"
      - "traefik.http.routers.telegrambotlaurenttransport.tls=true"
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'

  traefik:
    container_name: traefik
    image: traefik:v2.9
    ports:
      - 80:80
      - 8443:8443
      - 9443:9443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/etc/traefik/data
      - /home/laurent/certs:/etc/traefik/certs
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.traefik.rule=Host(`${HOST_URL}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure9"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8088"

      # Установка пароля для входа в админку
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD}"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"

      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=false"
    command:
      - "--api.dashboard=true"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entryPoints.ping.address=:8888"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure8.address=:8443"
      - "--entrypoints.websecure9.address=:9443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/data/tls.yml"
    healthcheck:
      test: [ "CMD", "wget", "http://127.0.0.1:8888/ping","--spider" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped